# import cv2
# image = cv2.imread("C:\\Users\\Asus\\Desktop\\dog.jpg")
# img1 = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
# img2 = cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
# img3 = cv2.cvtColor(image,cv2.COLOR_BGR2HLS)
# img4 = cv2.cvtColor(image,cv2.COLOR_BGR2LAB)
# img5 = cv2.cvtColor(image,cv2.COLOR_BGR2HLS)
# img6 = cv2.cvtColor(image,cv2.COLOR_BGR2HLS)
# cv2.imwrite("C:\\Users\\Asus\\Desktop\\Blue1_dog.jpg",img1)
# cv2.imwrite("C:\\Users\\Asus\\Desktop\\HSV2_dog.jpg",img2)
# cv2.imwrite("C:\\Users\\Asus\\Desktop\\HSV3_dog.jpg",img3)
# cv2.imwrite("C:\\Users\\Asus\\Desktop\\HSV4_dog.jpg",img4)
# cv2.imwrite("C:\\Users\\Asus\\Desktop\\HSV5_dog.jpg",img5)
# cv2.imwrite("C:\\Users\\Asus\\Desktop\\HSV6_dog.jpg",img6)
image = cv2.imread("C:\\Users\\Asus\\Desktop\\tanya'spic.jpg")
# img = cv2.cvtColor(image,cv2.COLOR_BAYER_BGGR2BGR)
# cv2.imwrite("C:\\Users\\Asus\\Desktop\\tanya'spic.jpg",img)